apiVersion: v1
kind: BuildConfig
metadata:
  name: cipipeline
  labels:
    name: cipipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "camelspringboot", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
    jenkinsfile: |-
          node {          
            stage("Build") {
              openshiftBuild buildConfig: 'camelspringboot', showBuildLogs: 'true'
            }

            stage("Deploy") {
              openshiftDeploy deploymentConfig: 'camelspringboot'
              openshiftVerifyDeployment deploymentConfig: 'camelspringboot', verbose: verbose
            }

            stage("Validate") {
              input message: "Test deployment. Approve?", id: "approval"
            }

            stage("Prepare Release") {
              openshiftTag srcStream: 'camelspringboot', srcTag: 'latest', destinationStream: 'camelspringboot', destinationTag: 'release', verbose: verbose
              
            }
          }
  output:
  resources:
  postCommit:
