apiVersion: v1
kind: BuildConfig
metadata:
  name: cipipeline
  labels:
    name: cipipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
    jenkinsfile: |-    
          def appName="${NAME}"
          def project=""
          def tag = "latest"
          def verbose="${VERBOSE}"

          node {
            project = env.PROJECT_NAME

            stage("Build") {
              echo "building tag ${tag}"
              openshiftBuild buildConfig: appName, showBuildLogs: "true", verbose: verbose
            }

            stage("Deploy Test") {
              openshiftTag srcStream: appName, srcTag: 'latest', destinationStream: appName, destinationTag: 'release', verbose: verbose
              openshiftVerifyDeployment deploymentConfig: "${appName}-${tag}", verbose: verbose
            }

            stage("Test") {
              input message: "Test deployment. Approve?", id: "approval"
            }
          }
  output:
  resources:
  postCommit:
