apiVersion: v1
kind: BuildConfig
metadata:
  name: cipipeline
  labels:
    name: cipipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
    jenkinsfile: |-    
          def appName="${NAME}"
          node {          
            stage("Build") {
              openshiftBuild buildConfig: appName, showBuildLogs: 'true'
            }

            stage("Deploy") {
              openshiftDeploy deploymentConfig: appName
              openshiftVerifyDeployment deploymentConfig: appName
            }

            stage("Validate") {
              input message: "Test deployment. Approve?", id: "approval"
            }

            stage("Prepare Release") {
              openshiftTag srcStream: appName, srcTag: 'latest', destinationStream: appName, destinationTag: 'release', verbose: verbose
              
            }
          }
  output:
  resources:
  postCommit:
